# Sample Streamlit secrets configuration for standard PostgreSQL
# Copy this to .streamlit/secrets.toml and update with your actual database credentials

[postgres]
# Standard PostgreSQL connection parameters
host = "localhost"              # Your PostgreSQL server host (e.g., "localhost", "192.168.1.100", "your-server.com")
port = "5432"                   # PostgreSQL port (default is 5432)
database = "lung_cancer_db"     # Your database name
user = "your_username"          # Your PostgreSQL username
password = "your_password"      # Your PostgreSQL password

# Optional SSL configuration (uncomment if needed)
# sslmode = "disable"           # For local development without SSL
# sslmode = "require"           # For production with SSL required
# sslmode = "prefer"            # Default - use SSL if available, fallback to non-SSL

# Example configurations for different setups:

# Local PostgreSQL (no SSL):
# host = "localhost"
# port = "5432" 
# database = "lung_cancer_db"
# user = "postgres"
# password = "your_local_password"
# sslmode = "disable"

# Remote PostgreSQL with SSL:
# host = "your-remote-server.com"
# port = "5432"
# database = "lung_cancer_db" 
# user = "your_remote_user"
# password = "your_remote_password"
# sslmode = "require"

# Docker PostgreSQL:
# host = "localhost"  # or container name if using docker-compose
# port = "5432"
# database = "lung_cancer_db"
# user = "postgres"
# password = "docker_password"
# sslmode = "disable"
